### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ragunathjawahar** [Dooskington/FighterDude2-RefactoringKata#1]
Hello, thank you for putting this kata out. I have a couple of questions.

1. What kind of license do you intend to license this kata?
2. Do you mind if I port this to Kotlin and create a separate kata (with attribution)?

Thank you, looking forward to hearing from you.

**Comment by Dooskington** [comment]
Hello!
I've added an MIT license to the repo.

A Kotlin port would be pretty cool. Go for it!

**Comment by ragunathjawahar** [comment]
Thank you very much!
